@export("SKIP_getArraySize")
fun getArraySize(arr: Array<Array<Int>>): UInt32 {
  UInt32::truncate(arr.size())
}

@export("SKIP_createByteArray")
fun createByteArray(size: UInt32): mutable Array<UInt8> {
  Array<UInt8>::mfill(size.toInt(), UInt8::truncate(0));
}

@export("SKIP_createFloatArray")
fun createFloatArray(size: UInt32): mutable Array<Float> {
  Array<Float>::mfill(size.toInt(), 0.0);
}

@export("SKIP_createUInt32Array")
fun createUInt32Array(size: UInt32): mutable Array<UInt32> {
  Array<UInt32>::mfill(size.toInt(), UInt32::truncate(0));
}

@export("SKIP_createIntArray")
fun createIntArray(size: Int): mutable Array<Int> {
  Array<Int>::mfill(size, 0);
}

module OCaml;

value class Memory(Array<UInt32>)
value class OCamlRoot(Int)

@export("SKIP_ocamlCreateContext")
fun createContext(): SKStore.Context {
  if (SKStore.gHasContext() == 0) {
    SKStore.gContextInit(SKStore.Context{});
  };
  SKStore.gUnsafeContextGet()
}

@export("SKIP_ocamlMCloneContext")
fun mcloneContext(context: readonly SKStore.Context): mutable SKStore.Context {
  context.mclone()
}

@export("SKIP_ocamlCloneContext")
fun cloneContext(context: readonly SKStore.Context): SKStore.Context {
  context.clone()
}

@export("SKIP_ocamlReplaceContext")
fun replaceContext(
  context: mutable SKStore.Context,
  saved: SKStore.Context,
): void {
  context.replaceFromSaved(saved);
}

class Key(value: String) extends SKStore.Key
class File(mem: Memory, root: OCamlRoot) extends SKStore.File

@export("SKIP_ocamlGetDummyFile")
fun getDummyFile(): File {
  File(Memory(Array[]), OCamlRoot(0))
}

@export("SKIP_ocamlCreateFile")
fun createFile(value: Memory, root: OCamlRoot): File {
  File(value, root)
}

@export("SKIP_ocamlGetRoot")
fun getRoot(file: File): OCamlRoot {
  file.root
}

@export("SKIP_ocamlCreateDirName")
fun createDirName(str: String): SKStore.DirName {
  SKStore.DirName::create(str)
}

@export("SKIP_ocamlCreateInputDir")
fun createInputDir(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
): void {
  context.unsafeMaybeGetEagerDir(dirName) match {
  | None() -> _ = context.mkdir(Key::keyType, File::type, dirName)
  | Some _ -> void
  }
}

@export("SKIP_ocamlWrite")
fun write(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
  key: String,
  value: File,
): void {
  context
    .unsafeGetEagerDir(dirName)
    .writeArray(context, Key(key), Array[value]);
}

@export("SKIP_ocamlArrayFileSize")
fun arrayFileSize(arr: Array<File>): Int {
  arr.size()
}

@export("SKIP_ocamlUnsafeGetArray")
fun unsafeGetArray(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
  key: String,
): Array<File> {
  context.unsafeGetEagerDir(dirName).getArrayRaw(Key(key)).map(value -> {
    value match {
    | v @ File _ -> v
    | _ -> invariant_violation("Unexpected value")
    }
  })
}

@export("SKIP_ocamlGetArray")
fun getArray(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
  key: String,
): Array<File> {
  SKStore.EHandle(Key::keyType, File::type, dirName).getArray(context, Key(key))
}

@cpp_extern("SKIP_saveDelayedCall")
native fun saveDelayedCall(dirName: String, key: String): void;

@cpp_extern("SKIP_getDelayedCall")
native fun getDelayedCall(dirName: String, key: String): Array<KeyFiles>;

@cpp_extern("SKIP_searchDelayedCall")
native fun searchDelayedCall(dirName: String, key: String): Int;

@cpp_extern("SKIP_getDelayedReads")
native fun getDelayedReads(dirName: String, key: String): Array<SKStore.Path>;

@cpp_extern("sk_is_save_reads_mode")
native fun isSaveReadsMode(): Int;

@export("SKIP_ocamlAddDirty")
fun addDirty(
  context: mutable SKStore.Context,
  parentName: SKStore.DirName,
  childName: SKStore.DirName,
  key: String,
): void {
  path = SKStore.Path::create(parentName, Key(key));
  context.!dirty = List.Cons(path, context.dirty);
  parentDir = context.unsafeGetEagerDir(parentName);
  childDir = context.unsafeGetEagerDir(childName);
  context.addToUpdate(
    childDir.timeStack,
    parentDir.time,
    SKStore.Arrow(parentName, childName),
  )
}

@export("SKIP_ocamlDelayedMap")
fun delayedMap(
  context: mutable SKStore.Context,
  parentDirName: SKStore.DirName,
  targetDirName: SKStore.DirName,
): Int {
  context.unsafeMaybeGetEagerDir(targetDirName) match {
  | None() ->
    handle = SKStore.EHandle(Key::keyType, File::type, parentDirName);
    _ = handle.map(
      Key::keyType,
      File::type,
      context,
      targetDirName,
      (context, writer, key, valueIter) ~> {
        if (isSaveReadsMode() != 0) {
          reads = getDelayedReads(targetDirName.toString(), key.value);
          for (read in reads) {
            debug(
              ("Saving read for", targetDirName.toString(), key.value, read),
            );
            context.addDep(read);
          };
          writer.setArray(key, valueIter.toArray());
          return void;
        };
        // WARNING: The following call to `saveDelayedCall` is
        // **extremely unsafe** and must be modified with great
        // caution. This function saves the passed
        // `targetDirName.toString()` and `key.value` outside of
        // the SKIP heap and obstack. It is critical that both
        // arguments point to objects that were allocated long
        // before this function was invoked, and that are
        // guaranteed to remain valid independently of the current
        // obstack state.
        //
        // If an object allocated in the current obstack were to be
        // passed here, it could be freed or moved by the garbage
        // collector without `saveDelayedCall` being aware, leading
        // to dangerous dangling pointers and potential memory
        // corruption.
        //
        // Any changes to this code must be reviewed with a deep
        // understanding of SKIP memory management and object
        // lifetimes.

        saveDelayedCall(targetDirName.toString(), key.value);
        writer.setArray(key, valueIter.toArray())
      },
    );
    0
  | Some _ -> 1
  }
}

@export("SKIP_ocamlCreateArrayFile")
fun createArrayFile(size: Int): mutable Array<File> {
  Array::mfill(size, File(Memory(Array[]), OCamlRoot(0)))
}

@export("SKIP_ocamlSetArrayFile")
fun setArrayFile(array: mutable Array<File>, idx: Int, file: File): void {
  array![idx] = file;
}

class KeyFiles(key: Key, files: Array<File>) extends SKStore.File

@export("SKIP_ocamlCreateKeyFiles")
fun createKeyFiles(key: String, files: Array<File>): KeyFiles {
  KeyFiles(Key(key), files)
}

@export("SKIP_ocamlCreateArrayKeyFiles")
fun createArrayKeyFiles(size: Int): mutable Array<KeyFiles> {
  Array::mfill(size, KeyFiles(Key(""), Array[]))
}

@export("SKIP_ocamlContextGetReads")
fun contextGetReads(context: readonly SKStore.Context): Array<SKStore.Path> {
  context.reads.toArray()
}

@export("SKIP_ocamlArrayKeyFilesSize")
fun arrayKeyFilesSize(arr: Array<KeyFiles>): Int {
  arr.size()
}

@export("SKIP_ocamlArrayKeyFilesGet")
fun arrayKeyFilesGet(arr: Array<KeyFiles>, idx: Int): KeyFiles {
  arr[idx]
}

@export("SKIP_ocamlKeyFilesGetKey")
fun keyFilesGetKey(keyFiles: KeyFiles): Key {
  keyFiles.key
}

@export("SKIP_ocamlKeyFilesGetFiles")
fun keyFilesGetFiles(keyFiles: KeyFiles): Array<File> {
  keyFiles.files
}

@export("SKIP_ocamlSetArrayKeyFiles")
fun setArrayKeyFiles(
  array: mutable Array<KeyFiles>,
  idx: Int,
  file: KeyFiles,
): void {
  array![idx] = file;
}

@cpp_extern("SKIP_ocamlCompareValues")
native fun ocamlCompareValues(v1: OCamlRoot, v2: OCamlRoot): Int;

@cpp_extern("SKIP_ocamlUnsafeCastFiles")
native fun unsafeCastFiles(v: Array<SKStore.File>): Array<File>;

@export("SKIP_ocamlMap")
fun map(
  context: mutable SKStore.Context,
  parentDirName: SKStore.DirName,
  targetDirName: SKStore.DirName,
  dedupDirName: SKStore.DirName,
): Int {
  context.unsafeMaybeGetEagerDir(targetDirName) match {
  | None() ->
    handle = SKStore.EHandle(Key::keyType, File::type, parentDirName);
    _ = handle
      .map(
        Key::keyType,
        File::type,
        context,
        targetDirName,
        (_context, writer, key, _valueIter) ~> {
          delayedCall = getDelayedCall(parentDirName.toString(), key.value);
          for (kv in delayedCall) {
            writer.setArray(kv.key, kv.files)
          }
        },
      )
      .map(
        Key::keyType,
        File::type,
        context,
        dedupDirName,
        (context, writer, key, valueIter) ~> {
          values = valueIter.toArray();
          context.unsafeMaybeGetEagerDir(dedupDirName) match {
          | None() -> writer.setArray(key, values)
          | Some(oldDir) ->
            oldValues = oldDir.getArrayRaw(key);
            if (oldValues.size() != values.size()) {
              writer.setArray(key, values);
              return void;
            };
            for (i in Range(0, values.size())) {
              if (
                ocamlCompareValues(
                  File::type(oldValues[i]).root,
                  File::type(values[i]).root,
                ) != 0
              ) {
                writer.setArray(key, values);
                return void;
              }
            };
            writer.setArray(key, unsafeCastFiles(oldValues))
          }
        },
      );
    0
  | Some _ -> 1
  }
}

@export("SKIP_ocamlSync")
fun sync(context: SKStore.Context, newContext: SKStore.Context): void {
  !newContext = newContext.unsafeForceReset();
  !context = SKStore.gContextSync(
    context.tick,
    context,
    newContext,
    None(),
    UInt32::truncate(0),
    None(),
  );
  SKStore.gUnsafeFree(context);
}

@export("SKIP_ocamlUpdate")
fun update(context: mutable SKStore.Context, dirName: String): void {
  context.updateDir(dirName);
}

@export("SKIP_ocamlUnion")
fun union(
  context: mutable SKStore.Context,
  dirName1: SKStore.DirName,
  dirName2: SKStore.DirName,
  targetName: SKStore.DirName,
): Int {
  context.unsafeMaybeGetEagerDir(targetName) match {
  | None() ->
    f = (_context, writer, key, valueIter) ~> {
      writer.setArray(key, valueIter.toArray());
    };
    _ = SKStore.EHandle::multiMap(
      Key::keyType,
      File::type,
      context,
      Array[
        (SKStore.EHandle(Key::keyType, File::type, dirName1), (f, None())),
        (SKStore.EHandle(Key::keyType, File::type, dirName2), (f, None())),
      ],
      targetName,
    );
    0
  | Some _ -> 1
  }
}

module end;
