@export("SKIP_getArraySize")
fun getArraySize(arr: Array<Array<Int>>): UInt32 {
  UInt32::truncate(arr.size())
}

@export("SKIP_createByteArray")
fun createByteArray(size: UInt32): mutable Array<UInt8> {
  Array<UInt8>::mfill(size.toInt(), UInt8::truncate(0));
}

@export("SKIP_createFloatArray")
fun createFloatArray(size: UInt32): mutable Array<Float> {
  Array<Float>::mfill(size.toInt(), 0.0);
}

@export("SKIP_createUInt32Array")
fun createUInt32Array(size: UInt32): mutable Array<UInt32> {
  Array<UInt32>::mfill(size.toInt(), UInt32::truncate(0));
}

@export("SKIP_createIntArray")
fun createIntArray(size: Int): mutable Array<Int> {
  Array<Int>::mfill(size, 0);
}

module OCaml;

value class Memory(Array<UInt32>)
value class OCamlRoot(Int)

@export("SKIP_ocamlCreateContext")
fun createContext(): SKStore.Context {
  if (SKStore.gHasContext() == 0) {
    SKStore.gContextInit(SKStore.Context{});
  };
  SKStore.gUnsafeContextGet()
}

@export("SKIP_ocamlMCloneContext")
fun mcloneContext(context: readonly SKStore.Context): mutable SKStore.Context {
  context.mclone()
}

@export("SKIP_ocamlCloneContext")
fun cloneContext(context: readonly SKStore.Context): SKStore.Context {
  context.clone()
}

@export("SKIP_ocamlReplaceContext")
fun replaceContext(
  context: mutable SKStore.Context,
  saved: SKStore.Context,
): void {
  context.replaceFromSaved(saved);
}

class Key(value: String) extends SKStore.Key
class File(mem: Memory, root: OCamlRoot) extends SKStore.File

@export("SKIP_ocamlGetDummyFile")
fun getDummyFile(): File {
  File(Memory(Array[]), OCamlRoot(0))
}

@export("SKIP_ocamlCreateFile")
fun createFile(value: Memory, root: OCamlRoot): File {
  File(value, root)
}

@export("SKIP_ocamlGetRoot")
fun getRoot(file: File): OCamlRoot {
  file.root
}

@export("SKIP_ocamlCreateDirName")
fun createDirName(str: String): SKStore.DirName {
  SKStore.DirName::create(str)
}

@export("SKIP_ocamlCreateInputDir")
fun createInputDir(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
): void {
  context.unsafeMaybeGetEagerDir(dirName) match {
  | None() -> _ = context.mkdir(Key::keyType, File::type, dirName)
  | Some _ -> void
  }
}

@export("SKIP_ocamlWrite")
fun write(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
  key: String,
  value: File,
): void {
  context
    .unsafeGetEagerDir(dirName)
    .writeArray(context, Key(key), Array[value]);
}

@export("SKIP_ocamlArrayFileSize")
fun arrayFileSize(arr: Array<File>): Int {
  arr.size()
}

@export("SKIP_ocamlUnsafeGetArray")
fun unsafeGetArray(
  context: mutable SKStore.Context,
  dirName: SKStore.DirName,
  key: String,
): Array<File> {
  context.unsafeGetEagerDir(dirName).getArrayRaw(Key(key)).map(value -> {
    value match {
    | v @ File _ -> v
    | _ -> invariant_violation("Unexpected value")
    }
  })
}

@cpp_extern("SKIP_saveDelayedCall")
native fun saveDelayedCall(dirName: String, key: String): void;

@export("SKIP_ocamlDelayedMap")
fun delayedMap(
  context: mutable SKStore.Context,
  parentDirName: SKStore.DirName,
  targetDirName: SKStore.DirName,
): Int {
  context.unsafeMaybeGetEagerDir(targetDirName) match {
  | None() ->
    handle = SKStore.EHandle(Key::keyType, File::type, parentDirName);
    _ = handle.map(
      Key::keyType,
      File::type,
      context,
      targetDirName,
      (_context, writer, key, valueIter) ~> {
        debug(("PMAP", targetDirName.toString(), key));
        saveDelayedCall(targetDirName.toString(), key.value);
        writer.setArray(key, valueIter.toArray())
      },
    );
    0
  | Some _ -> 1
  }
}

@export("SKIP_ocamlCreateArrayFile")
fun createArrayFile(size: Int): mutable Array<File> {
  Array::mfill(size, File(Memory(Array[]), OCamlRoot(0)))
}

@export("SKIP_ocamlSetArrayFile")
fun setArrayFile(array: mutable Array<File>, idx: Int, file: File): void {
  array![idx] = file;
}

class KeyFiles(key: Key, files: Array<File>) extends SKStore.File

@cpp_extern("SKIP_getDelayedCall")
native fun getDelayedCall(dirName: String, key: String): Array<KeyFiles>;

@cpp_extern("SKIP_getDelayedReads")
native fun getDelayedReads(dirName: String, key: String): Array<SKStore.Path>;

@export("SKIP_ocamlCreateKeyFiles")
fun createKeyFiles(key: String, files: Array<File>): KeyFiles {
  KeyFiles(Key(key), files)
}

@export("SKIP_ocamlCreateArrayKeyFiles")
fun createArrayKeyFiles(size: Int): mutable Array<KeyFiles> {
  Array::mfill(size, KeyFiles(Key(""), Array[]))
}

@export("SKIP_ocamlContextGetReads")
fun contextGetReads(context: readonly SKStore.Context): Array<SKStore.Path> {
  context.reads.toArray()
}

@export("SKIP_ocamlArrayKeyFilesSize")
fun arrayKeyFilesSize(arr: Array<KeyFiles>): Int {
  arr.size()
}

@export("SKIP_ocamlArrayKeyFilesGet")
fun arrayKeyFilesGet(arr: Array<KeyFiles>, idx: Int): KeyFiles {
  arr[idx]
}

@export("SKIP_ocamlKeyFilesGetKey")
fun keyFilesGetKey(keyFiles: KeyFiles): Key {
  keyFiles.key
}

@export("SKIP_ocamlKeyFilesGetFiles")
fun keyFilesGetFiles(keyFiles: KeyFiles): Array<File> {
  keyFiles.files
}

@export("SKIP_ocamlSetArrayKeyFiles")
fun setArrayKeyFiles(
  array: mutable Array<KeyFiles>,
  idx: Int,
  file: KeyFiles,
): void {
  array![idx] = file;
}

@export("SKIP_ocamlDebugArrayKeyFiles")
fun debugArrayKeyFiles(arr: Array<KeyFiles>): void {
  debug(arr);
}

@export("SKIP_ocamlDebugKeyFiles")
fun debugKeyFiles(v: KeyFiles): void {
  debug(v);
}

@export("SKIP_ocamlDebugArrayFiles")
fun debugFiles(v: Array<File>): void {
  debug(v);
}

@export("SKIP_ocamlDebugFile")
fun debugFile(v: File): void {
  debug(v);
}

@cpp_extern("SKIP_ocamlCompareValues")
native fun ocamlCompareValues(v1: OCamlRoot, v2: OCamlRoot): Int;

@cpp_extern("SKIP_ocamlUnsafeCastFiles")
native fun unsafeCastFiles(v: Array<SKStore.File>): Array<File>;

@export("SKIP_ocamlMap")
fun map(
  context: mutable SKStore.Context,
  parentDirName: SKStore.DirName,
  targetDirName: SKStore.DirName,
  dedupDirName: SKStore.DirName,
): Int {
  context.unsafeMaybeGetEagerDir(targetDirName) match {
  | None() ->
    handle = SKStore.EHandle(Key::keyType, File::type, parentDirName);
    _ = handle
      .map(
        Key::keyType,
        File::type,
        context,
        targetDirName,
        (context, writer, key, _valueIter) ~> {
          delayedCall = getDelayedCall(parentDirName.toString(), key.value);
          reads = getDelayedReads(parentDirName.toString(), key.value);
          for (read in reads) {
            context.addDep(read);
          };
          for (kv in delayedCall) {
            writer.setArray(kv.key, kv.files)
          }
        },
      )
      .map(
        Key::keyType,
        File::type,
        context,
        dedupDirName,
        (context, writer, key, valueIter) ~> {
          values = valueIter.toArray();
          context.unsafeMaybeGetEagerDir(dedupDirName) match {
          | None() -> writer.setArray(key, values)
          | Some(oldDir) ->
            debug(("Comparing"));
            oldValues = oldDir.getArrayRaw(key);
            if (oldValues.size() != values.size()) {
              debug(("Different sizes"));
              writer.setArray(key, values);
              return void;
            };
            for (i in Range(0, values.size())) {
              if (
                ocamlCompareValues(
                  File::type(oldValues[i]).root,
                  File::type(values[i]).root,
                ) != 0
              ) {
                debug(("Different values", i));
                writer.setArray(key, values);
                return void;
              }
            };
            debug(("Same values"));
            writer.setArray(key, unsafeCastFiles(oldValues))
          }
        },
      );
    0
  | Some _ -> 1
  }
}

@export("SKIP_ocamlSync")
fun sync(context: SKStore.Context, newContext: SKStore.Context): void {
  !context = SKStore.gContextSync(
    context.tick,
    context,
    newContext,
    None(),
    UInt32::truncate(0),
    None(),
  );
  SKStore.gUnsafeFree(context);
}

@export("SKIP_ocamlUpdate")
fun update(context: mutable SKStore.Context, dirName: String): void {
  context.updateDir(dirName);
}

module end;
